use std::math;
use std::math::consts::PI;
use std::collections::set;

let test = PI;
test = "aidin53";

println(sin(3));
println(mul(3, 6));

let t = "x";
let x = "aidin53".len();
if true {
    let x = 39;
    let names = ["aidin", "aida", "hamid", "reza"];

    println("names list: " + names.at(1));
    println("set of nums: " + set([1, 2, 1, 2, 1, 2, 4, 4, 1, 2, 3, 4, 5, 6]));
    # println(x.pow(56));

    if true {
        let x = 4;
        println(test);
        # println(x.to_string().len());
    } else if true {
        let x = false.to_string();
    } else {
        let x = 499;
    }
}
# let x = "aidin53";
# println(t); 

